export const ANALYTICS_EVENT_NAMES = [
  "artifact_toast_shown",
  "artifact_unlock_collection_clicked",
  "artifact_unlock_continue_clicked",
  "artifact_unlock_modal_shown",
  "artifact_unlock_queued",
  "campaign_progress",
  "campaign_card_impression",
  "campaign_completed",
  "campaign_entered",
  "campaign_first_level_completed",
  "campaign_report_cta_clicked",
  "campaign_report_shown",
  "campaign_selected",
  "campaign_unlocked",
  "collection_artifact_viewed",
  "collection_opened",
  "collection_replay_level_clicked",
  "daily_opened",
  "daily_reward_claimed",
  "daily_start_clicked",
  "difference_found",
  "fatal_error",
  "game_open",
  "game_ready",
  "game_ready_timing",
  "hint_revealed",
  "interstitial_close",
  "interstitial_eligible",
  "interstitial_error",
  "interstitial_open",
  "interstitial_request",
  "level_attempt_end",
  "level_attempt_start",
  "level_card_clicked",
  "level_complete",
  "level_next_clicked",
  "level_resume",
  "level_time_extended",
  "locked_campaign_clicked",
  "magnifiers_spent",
  "onboarding_abandoned",
  "onboarding_completed",
  "onboarding_first_interaction",
  "onboarding_impression",
  "onboarding_start_clicked",
  "review_native_closed",
  "review_native_error",
  "review_native_requested",
  "review_native_sent",
  "review_native_unavailable",
  "review_prompt_closed",
  "review_prompt_eligible",
  "review_prompt_later_clicked",
  "review_prompt_review_clicked",
  "review_prompt_shown",
  "rewarded_hint_closed",
  "rewarded_hint_failed",
  "rewarded_hint_offer_opened",
  "rewarded_hint_requested",
  "rewarded_hint_rewarded",
  "save_load_result",
  "save_write_failed",
  "scene_load_result",
  "screen_view",
  "settings_closed",
  "settings_comparator_scheme_changed",
  "settings_language_changed",
  "settings_opened",
  "setting_interest_selected",
] as const;

export type AnalyticsEventName = (typeof ANALYTICS_EVENT_NAMES)[number];

export const ANALYTICS_GOALS = ANALYTICS_EVENT_NAMES.map((event) => ({
  event,
  name: `Anomaly Archive: ${event}`,
  identifier: `aa_${event}`,
}));

const analyticsEventNameSet = new Set<string>(ANALYTICS_EVENT_NAMES);

export function isAnalyticsEventName(
  value: string,
): value is AnalyticsEventName {
  return analyticsEventNameSet.has(value);
}
